### ISSUE TITLE
Liveness check fails

### ISSUE THREAD

**Issue by tekumara** [fizzbee-io/fizzbee#109] opened 2024-11-24 07:08 UTC
The following spec:

```
---
# disabled because of https://github.com/fizzbee-io/fizzbee/issues/106
deadlock_detection: false
options:
    max_actions: 100
action_options:
    Human.Input:
        max_actions: 2
        max_concurrent_actions: 1
    Worker.Receive:
        max_actions: 2
        max_concurrent_actions: 1
---


always eventually assertion UIMatches:
  # accumulate history that isn't sorry, or before sorry
  mod_sorry = []
  history = ui.history
  for i in range(len(history)):
    if history[i][0] != "Sorry" and (i+1 == len(history) or history[i+1][0] != "Sorry"):
      mod_sorry.append(history[i])

  return mod_sorry == api.history or history[-1][0] == "Sorry"


def next_letter(letter):
  # next lowercase letter, wrapping back to a when reaching z
  return chr((ord(letter) - 97 + 1) % 26 + 97)


role Human:
  # model Human side of the conversation

  action Input:
    # start the conversation with "a" or reply to the AI
    # with the next letter
    input = None
    response = ui.history[-1] if ui.history else None
    if not response or response[0] == "Sorry":
      input = ("Human","a")
    elif response[0] == "AI":
      input = ("Human", next_letter(response[1]))

    if input:
      ui.input(input)

role ChatUI:
  action Init:
    self.history = []

  func input(input):
    last_ai = None
    # find last reply id from assistant
    for i in reversed(range(len(self.history))):
      if self.history[i][0] == "AI":
        last_ai = self.history[i][2]
        break
    human_msg_id = len(self.history)+1
    message = (input[0], input[1], last_ai, human_msg_id)

    atomic:
      self.history.append(message)
      sqs.send_message(message)

  func callback(response):
    # drop late responses
    human_msg_id = response[3]
    if human_msg_id == len(self.history):
      self.history.append(response)

  fair action SorryTimer:
    # if we haven't got a response from the API, say sorry
    if self.history and self.history[-1][0] == "Human":
      self.history.append(("Sorry", None, None))

role SQS:
  action Init:
    self.fifo = []

  func send_message(msg):
    sqs.fifo.append(msg)

  func receive_message():
    return sqs.fifo[0] if sqs.fifo else None

  func receive_message_once():
    return sqs.fifo.pop(0) if sqs.fifo else None

  func delete_message(msg):
    atomic:
      if msg in sqs.fifo:
        sqs.fifo.remove(msg)

role Worker:
    action Init:
        pass

    action Receive:
      msg = sqs.receive_message_once()
      if msg:
          reply = api.message(msg)
          ui.callback(reply)

role API:
  action Init:
    self.history = []

  func message(msg):
    kind, text, last_ai, human_msg_id = msg
    if last_ai:
      # drop any AI replies the chat ui hasn't seen
      self.history = self.history[:last_ai+1]
    else:
      # receiving message that's never seen an assistant reply
      # so reset
      self.history = []

    self.history.append(msg)
    reply = llm.chat(text)

    reply_id = len(self.history)
    response = (reply[0], reply[1], reply_id, human_msg_id)
    self.history.append(response)
    return response

role LLM:
  # model LLM side of the conversation

  func chat(text):
    # return next letter in the convo
    return ("AI", next_letter(text))

action Init:
  h = Human()
  ui = ChatUI()
  sqs = SQS()
  w = Worker()
  api = API()
  llm = LLM()

```
fails with:

```
FAILED: Liveness check failed
Invariant: UIMatches
------
Init
--
state: {"api":"role API#0 (fields(history = []))","h":"role Human#0 (fields())","llm":"role LLM#0 (fields())","sqs":"role SQS#0 (fields(fifo = []))","ui":"role ChatUI#0 (fields(history = []))","w":"role Worker#0 (fields())"}
------
Human#0.Input
--
state: {"api":"role API#0 (fields(history = []))","h":"role Human#0 (fields())","llm":"role LLM#0 (fields())","sqs":"role SQS#0 (fields(fifo = []))","ui":"role ChatUI#0 (fields(history = []))","w":"role Worker#0 (fields())"}
------
thread-0
--
state: {"api":"role API#0 (fields(history = []))","h":"role Human#0 (fields())","llm":"role LLM#0 (fields())","sqs":"role SQS#0 (fields(fifo = []))","ui":"role ChatUI#0 (fields(history = []))","w":"role Worker#0 (fields())"}
------
thread-0
--
state: {"api":"role API#0 (fields(history = []))","h":"role Human#0 (fields())","llm":"role LLM#0 (fields())","sqs":"role SQS#0 (fields(fifo = []))","ui":"role ChatUI#0 (fields(history = []))","w":"role Worker#0 (fields())"}
------
thread-0
--
state: {"api":"role API#0 (fields(history = []))","h":"role Human#0 (fields())","llm":"role LLM#0 (fields())","sqs":"role SQS#0 (fields(fifo = []))","ui":"role ChatUI#0 (fields(history = []))","w":"role Worker#0 (fields())"}
------
thread-0
--
state: {"api":"role API#0 (fields(history = []))","h":"role Human#0 (fields())","llm":"role LLM#0 (fields())","sqs":"role SQS#0 (fields(fifo = []))","ui":"role ChatUI#0 (fields(history = []))","w":"role Worker#0 (fields())"}
------
thread-0
--
state: {"api":"role API#0 (fields(history = []))","h":"role Human#0 (fields())","llm":"role LLM#0 (fields())","sqs":"role SQS#0 (fields(fifo = []))","ui":"role ChatUI#0 (fields(history = []))","w":"role Worker#0 (fields())"}
------
thread-0
--
state: {"api":"role API#0 (fields(history = []))","h":"role Human#0 (fields())","llm":"role LLM#0 (fields())","sqs":"role SQS#0 (fields(fifo = [(\"Human\", \"a\", None, 1)]))","ui":"role ChatUI#0 (fields(history = [(\"Human\", \"a\", None, 1)]))","w":"role Worker#0 (fields())"}
------
Human#0.Input
--
state: {"api":"role API#0 (fields(history = []))","h":"role Human#0 (fields())","llm":"role LLM#0 (fields())","sqs":"role SQS#0 (fields(fifo = [(\"Human\", \"a\", None, 1)]))","ui":"role ChatUI#0 (fields(history = [(\"Human\", \"a\", None, 1)]))","w":"role Worker#0 (fields())"}
------
thread-0
--
state: {"api":"role API#0 (fields(history = []))","h":"role Human#0 (fields())","llm":"role LLM#0 (fields())","sqs":"role SQS#0 (fields(fifo = [(\"Human\", \"a\", None, 1)]))","ui":"role ChatUI#0 (fields(history = [(\"Human\", \"a\", None, 1)]))","w":"role Worker#0 (fields())"}
------
Worker#0.Receive
--
state: {"api":"role API#0 (fields(history = []))","h":"role Human#0 (fields())","llm":"role LLM#0 (fields())","sqs":"role SQS#0 (fields(fifo = []))","ui":"role ChatUI#0 (fields(history = [(\"Human\", \"a\", None, 1)]))","w":"role Worker#0 (fields())"}
------
stutter
--
state: {"api":"role API#0 (fields(history = []))","h":"role Human#0 (fields())","llm":"role LLM#0 (fields())","sqs":"role SQS#0 (fields(fifo = []))","ui":"role ChatUI#0 (fields(history = [(\"Human\", \"a\", None, 1)]))","w":"role Worker#0 (fields())"}
------
```

But I can't understand why. It seems to me like the invariant will be satisfied if the checker continues? Am I missing something here?

**Comment by jp-fizzbee** [comment] 2024-11-30 21:14
This is a combination of two issues. 
1. The stuttering and liveness behavior was counter intuitive.
  I [fixed this issue](https://github.com/fizzbee-io/fizzbee/pull/111), just a few days ago. But I just upgraded the frontend.
2. There is another counter intuitive issue, I am not sure what correct behavior must be. 
https://docs.google.com/document/d/145D7LmIMMPteuSczy3PlFYw_FDCUAXs7cA7ML3JTUvA/edit?usp=sharing
The issue is, after a yield step, if there is another instruction, and that instruction is not enabled, the current behavior is, it will be treated equivalent to wait until that instruction becomes enabled. This definitely is counter intuitive. 

For your example: The possible fixes are either:
1. Set the max_concurrent_actions for the global level to 2. (That way, even if Worker.Receive and Human.Input are stuck waiting for each other, the ChatUI.SorryTimer action has another thread to execute.)
2. Or, add an else block to the Human.Input.
   ```
    if input:
      ui.input(input)
    else:
      pass
   ```

---
For the second issue, I documented, what do you think should be the intended behavior?

**Comment by jp-fizzbee** [comment] 2024-12-06 05:21
Oops, my mistake. The default for max_concurrent_actions: 2. So you need to increase it to `max_concurrent_actions: 3`

**Comment by jp-fizzbee** [comment] 2024-12-06 10:39
Let me know if this works and if you are okay to close this issue.

**Comment by tekumara** [comment] 2024-12-07 23:18
Yes setting `max_concurrent_actions: 3` works - thank you.

When does a disabled action wait and consume a concurrency slot?

In some cases it doesn't, eg: a trivial action like:

```
  action Disabled:
    pass
    require False
```

Doesn't seem to consume a concurrency slot.

**Comment by jayaprabhakar** [comment] 2024-12-08 02:06
Obviously, disabled action implies that action can't or doesn't happen.

An action will be consuming a thread or a slot of concurrency from the start of the action until it ends -  either successful completion or crash.

**Comment by tekumara** [comment] 2024-12-08 02:20
I would think so too. Except in the case that the above were:

~~~
    require input
    ui.input(input)
~~~

Then when the action is disabled the only way to avoid stutter is to increase global concurrency to 3. Implying a disabled action does consume a thread.

What am I missing?

**Comment by jayaprabhakar** [comment] 2024-12-08 16:31
That's a great question. Let me try to explain how it works and let me know what's the best way to document this concisely.

Take a look at this tiny example. The action Add has two steps each increment variable a once by 1.

```
---
deadlock_detection: false
options:
    crash_on_yield: false
    max_actions: 1
---


action Init:
  a = 0


action Add:
  a += 1
  # yield point here between these two lines 
  a += 1
  


```

When you run this, you'll see a total of 3 states. 
- Init state.
- Add called, incremented a by 1 and reached the yield point. 
- The thread resumed and incremented a again. 

So the add action has two state transitions.

If the same add action was atomic, then the add action would be in a single transition.

The `require` statement applies to each transition not each action. 

In atomic action, the entire action is a single transition. So require False implies the only action itself is not enabled. 

In non atomic action, if the first transition was disabled, it's like the action itself never happened. 
If the first one was enabled but the second transition is disabled, then the first action has happened. And consumes the concurrency slot / thread.

**Closed** 2024-12-12 07:13 UTC

**Comment by tekumara** [comment] 2024-12-14 09:53
Thank you, I think I understand now! Would be great to capture this in [the docs](https://fizzbee.io/tutorials/guard-clause/).

**Comment by tekumara** [comment] 2025-01-27 05:49
FYI - for the record, the following workaround:
```
 if input:
   ui.input(input)
 else:
   pass
```
is no longer required as of #126
